# Generated by Django 4.2.6 on 2023-10-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveries',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ingredientitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id']},
        ),
    ]
