# Generated by Django 4.2.6 on 2023-12-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_orders_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
