# Generated by Django 4.2.6 on 2023-12-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_store_alter_newuser_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
