# Generated by Django 4.2.6 on 2023-12-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
