# Generated by Django 4.2.6 on 2023-12-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newuser_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_admin',
            new_name='is_manager',
        ),
    ]
